#define LANG_NAME                        0
#define STRFTIME_DATE_TIME_FORMAT        1
#define STRFTIME_LONG_DATE_FORMAT        2
#define STRFTIME_SHORT_DATE_FORMAT       3
#define STRFTIME_DAYS_SHORT              4
#define STRFTIME_DAYS_LONG               5
#define STRFTIME_MONTHS_SHORT            6
#define STRFTIME_MONTHS_LONG             7
#define COMMA_SPACE                      8
#define USER_RECORD_NOT_FOUND            9
#define UNKNOWN_COMMAND                  10
#define UNKNOWN_COMMAND_HELP             11
#define SYNTAX_ERROR                     12
#define MORE_INFO                        13
#define NO_HELP_AVAILABLE                14
#define BAD_USERHOST_MASK                15
#define BAD_EXPIRY_TIME                  16
#define SERVICE_OFFLINE                  17
#define READ_ONLY_MODE                   18
#define ACCESS_DENIED                    19
#define PERMISSION_DENIED                20
#define PASSWORD_INCORRECT               21
#define MORE_OBSCURE_PASSWORD            22
#define PASSWORD_TRUNCATED               23
#define NICK_NOT_REGISTERED              24
#define NICK_NOT_REGISTERED_HELP         25
#define NICK_SUSPENDED                   26
#define NICK_IS_SUSPENDED                27
#define NICK_IS_REACTIVED                28
#define NICK_X_NOT_REGISTERED            29
#define NICK_X_NOT_IN_USE                30
#define NICK_X_FORBIDDEN                 31
#define NICK_X_SUSPENDED                 32
#define CHAN_X_NOT_REGISTERED            33
#define CHAN_X_NOT_IN_USE                34
#define CHAN_X_FORBIDDEN                 35
#define CHAN_X_SUSPENDED                 36
#define NICK_IDENTIFY_REQUIRED           37
#define CHAN_IDENTIFY_REQUIRED           38
#define NICK_IS_REGISTERED               39
#define NICK_IS_SECURE                   40
#define NICK_MAY_NOT_BE_USED             41
#define DISCONNECT_IN_1_MINUTE           42
#define DISCONNECT_IN_20_SECONDS         43
#define DISCONNECT_NOW                   44
#define FORCENICKCHANGE_IN_1_MINUTE      45
#define FORCENICKCHANGE_IN_20_SECONDS    46
#define FORCENICKCHANGE_NOW              47
#define NICK_REGISTER_SYNTAX             48
#define NICK_REGISTRATION_DISABLED       49
#define NICK_REGISTRATION_FAILED         50
#define NICK_REG_PLEASE_WAIT             51
#define NICK_CANNOT_BE_REGISTERED        52
#define NICK_ALREADY_REGISTERED          53
#define NICK_MAIL_INVALID                54
#define NICK_MAIL_ANONYMOUS              55
#define NICK_MAIL_ABUSE                  56
#define NICK_REGISTERED                  57
#define NICK_PASSWORD_IS                 58
#define NICK_IN_MAIL                     59
#define NICK_IDENTIFY_SYNTAX             60
#define NICK_IDENTIFY_FAILED             61
#define NICK_IDENTIFY_SUCCEEDED          62
#define NICK_IDENTIFY_X_MODE_R           63
#define NICK_IS_IDENTIFIED               64
#define NICK_DROP_SYNTAX                 65
#define NICK_DROP_DISABLED               66
#define NICK_DROP_FORBIDDEN              67
#define NICK_DROPPED                     68
#define NICK_X_DROPPED                   69
#define NICK_SET_SYNTAX                  70
#define NICK_SET_SERVADMIN_SYNTAX        71
#define NICK_SET_DISABLED                72
#define NICK_SET_UNKNOWN_OPTION          73
#define NICK_SET_UNKNOWN_OPTION_OR_BAD_NICK 74
#define NICK_SET_PASSWORD_FAILED         75
#define NICK_SET_PASSWORD_CHANGED        76
#define NICK_SET_PASSWORD_CHANGED_TO     77
#define NICK_SET_URL_CHANGED             78
#define NICK_SET_URL_UNSET               79
#define NICK_SET_EMAIL_CHANGED           80
#define NICK_SET_EMAIL_UNSET             81
#define NICK_SET_LANGUAGE_SYNTAX         82
#define NICK_SET_LANGUAGE_UNKNOWN        83
#define NICK_SET_LANGUAGE_CHANGED        84
#define NICK_SET_KILL_SYNTAX             85
#define NICK_SET_KILL_IMMED_SYNTAX       86
#define NICK_SET_KILL_ON                 87
#define NICK_SET_KILL_QUICK              88
#define NICK_SET_KILL_IMMED              89
#define NICK_SET_KILL_IMMED_DISABLED     90
#define NICK_SET_KILL_OFF                91
#define NICK_SET_SECURE_SYNTAX           92
#define NICK_SET_SECURE_ON               93
#define NICK_SET_SECURE_OFF              94
#define NICK_SET_PRIVATE_SYNTAX          95
#define NICK_SET_PRIVATE_ON              96
#define NICK_SET_PRIVATE_OFF             97
#define NICK_SET_HIDE_SYNTAX             98
#define NICK_SET_HIDE_EMAIL_ON           99
#define NICK_SET_HIDE_EMAIL_OFF          100
#define NICK_SET_HIDE_MASK_ON            101
#define NICK_SET_HIDE_MASK_OFF           102
#define NICK_SET_HIDE_QUIT_ON            103
#define NICK_SET_HIDE_QUIT_OFF           104
#define NICK_SET_VHOST_SYNTAX            105
#define NICK_SET_VHOST_ON                106
#define NICK_SET_VHOST_OFF               107
#define NICK_MUST_BE_ON_BDD              108
#define NICK_SET_BDD_SYNTAX              109
#define NICK_SET_BDD_ON                  110
#define NICK_SET_BDD_OFF                 111
#define NICK_BDD_NEW_REG                 112
#define NICK_SET_NOEXPIRE_SYNTAX         113
#define NICK_SET_NOEXPIRE_ON             114
#define NICK_SET_NOEXPIRE_OFF            115
#define NICK_INFO_SERV_OPER              116
#define NICK_INFO_SERV_ADMIN             117
#define NICK_INFO_SERV_ROOT              118
#define NICK_DO_INFO_OVER_OPER           119
#define NICK_ACCESS_SYNTAX               120
#define NICK_ACCESS_ALREADY_PRESENT      121
#define NICK_ACCESS_REACHED_LIMIT        122
#define NICK_ACCESS_ADDED                123
#define NICK_ACCESS_NOT_FOUND            124
#define NICK_ACCESS_DELETED              125
#define NICK_ACCESS_LIST                 126
#define NICK_ACCESS_LIST_X               127
#define NICK_LINK_SYNTAX                 128
#define NICK_LINK_DISABLED               129
#define NICK_LINK_FAILED                 130
#define NICK_NO_LINK_SAME                131
#define NICK_LINK_CIRCULAR               132
#define NICK_LINKED                      133
#define NICK_UNLINK_SYNTAX               134
#define NICK_UNLINK_FAILED               135
#define NICK_NOT_LINKED                  136
#define NICK_UNLINKED                    137
#define NICK_X_NOT_LINKED                138
#define NICK_X_UNLINKED                  139
#define NICK_LISTLINKS_SYNTAX            140
#define NICK_LISTLINKS_HEADER            141
#define NICK_LISTLINKS_FOOTER            142
#define NICK_INFO_SYNTAX                 143
#define NICK_INFO_LINKED                 144
#define NICK_INFO_SUSPENDED              145
#define NICK_INFO_REALNAME               146
#define NICK_INFO_ADDRESS                147
#define NICK_INFO_ADDRESS_ONLINE         148
#define NICK_INFO_ADDRESS_ONLINE_NOHOST  149
#define NICK_INFO_TIME_REGGED            150
#define NICK_INFO_LAST_SEEN              151
#define NICK_INFO_LAST_QUIT              152
#define NICK_INFO_URL                    153
#define NICK_INFO_EMAIL                  154
#define NICK_INFO_OPTIONS                155
#define NICK_INFO_OPT_KILL               156
#define NICK_INFO_OPT_SECURE             157
#define NICK_INFO_OPT_PRIVATE            158
#define NICK_INFO_OPT_NONE               159
#define NICK_INFO_OPT_BDD                160
#define NICK_INFO_NO_EXPIRE              161
#define NICK_INFO_LINKS                  162
#define NICK_LIST_SYNTAX                 163
#define NICK_LIST_SERVADMIN_SYNTAX       164
#define NICK_LIST_HEADER                 165
#define NICK_LIST_HIDDEN                 166
#define NICK_LIST_FORBIDDEN              167
#define NICK_LIST_SUSPENDED              168
#define NICK_LIST_NORMAL                 169
#define NICK_LIST_RESULTS                170
#define NICK_RECOVER_SYNTAX              171
#define NICK_NO_RECOVER_SELF             172
#define NICK_RECOVERED                   173
#define NICK_RELEASE_SYNTAX              174
#define NICK_RELEASE_NOT_HELD            175
#define NICK_RELEASED                    176
#define NICK_USERIP_SYNTAX               177
#define NICK_USERIP_CHECK_OK             178
#define NICK_USERIP_CHECK_NO             179
#define NICK_GHOST_SYNTAX                180
#define NICK_NO_GHOST_SELF               181
#define NICK_GHOST_KILLED                182
#define NICK_STATUS_OFFLINE              183
#define NICK_STATUS_NOT_REGISTRED        184
#define NICK_STATUS_NOT_IDENTIFIED       185
#define NICK_STATUS_RECOGNIZED           186
#define NICK_STATUS_IDENTIFIED           187
#define NICK_STATUS_SUSPENDED            188
#define NICK_STATUS_ID_BDD               189
#define NICK_SENDPASS_SYNTAX             190
#define NICK_SENDPASS_SUCCEEDED          191
#define NICK_GETPASS_SYNTAX              192
#define NICK_GETPASS_UNAVAILABLE         193
#define NICK_GETPASS_PASSWORD_IS         194
#define NICK_IS_A_SERVICE                195
#define NICK_SUSPEND_SYNTAX              196
#define NICK_SUSPEND_FORBIDDEN           197
#define NICK_SUSPEND_SUSPENDED           198
#define NICK_SUSPEND_OPER                199
#define NICK_SUSPEND_SUCCEEDED           200
#define NICK_SUSPEND_FAILED              201
#define NICK_UNSUSPEND_SYNTAX            202
#define NICK_SUSPEND_NOT_SUSPEND         203
#define NICK_UNSUSPEND_SUCCEEDED         204
#define NICK_UNSUSPEND_FAILED            205
#define NICK_FORBID_SYNTAX               206
#define NICK_FORBID_FORBIDDEN            207
#define NICK_FORBID_SUCCEEDED            208
#define NICK_FORBID_FAILED               209
#define NICK_UNFORBID_SYNTAX             210
#define NICK_UNFORBID_NOT_FORBID         211
#define NICK_UNFORBID_SUCCEEDED          212
#define NICK_UNFORBID_FAILED             213
#define CHAN_LEVEL_AUTOOP                214
#define CHAN_LEVEL_AUTOVOICE             215
#define CHAN_LEVEL_AUTODEOP              216
#define CHAN_LEVEL_AUTODEVOICE           217
#define CHAN_LEVEL_NOJOIN                218
#define CHAN_LEVEL_OPDEOP                219
#define CHAN_LEVEL_VOICEDEVOICE          220
#define CHAN_LEVEL_INVITE                221
#define CHAN_LEVEL_KICK                  222
#define CHAN_LEVEL_BAN                   223
#define CHAN_LEVEL_UNBAN                 224
#define CHAN_LEVEL_AKICK                 225
#define CHAN_LEVEL_SET                   226
#define CHAN_LEVEL_CLEAR                 227
#define CHAN_LEVEL_RESET                 228
#define CHAN_LEVEL_ACCESS_LIST           229
#define CHAN_LEVEL_ACCESS_CHANGE         230
#define CHAN_LEVEL_MEMO                  231
#define CHAN_IS_REGISTERED               232
#define CHAN_NOT_ALLOWED_OP              233
#define CHAN_MAY_NOT_BE_USED             234
#define CHAN_NOT_ALLOWED_TO_JOIN         235
#define CHAN_REGISTER_SYNTAX             236
#define CHAN_REGISTER_DISABLED           237
#define CHAN_REGISTER_NOT_LOCAL          238
#define CHAN_MUST_REGISTER_NICK          239
#define CHAN_MUST_IDENTIFY_NICK          240
#define CHAN_MAY_NOT_BE_REGISTERED       241
#define CHAN_ALREADY_REGISTERED          242
#define CHAN_MUST_BE_CHANOP              243
#define CHAN_REACHED_CHANNEL_LIMIT       244
#define CHAN_EXCEEDED_CHANNEL_LIMIT      245
#define CHAN_REGISTRATION_FAILED         246
#define CHAN_REGISTERED                  247
#define CHAN_PASSWORD_IS                 248
#define CHAN_IDENTIFY_SYNTAX             249
#define CHAN_IDENTIFY_FAILED             250
#define CHAN_IDENTIFY_SUCCEEDED          251
#define CHAN_DROP_SYNTAX                 252
#define CHAN_DROP_DISABLED               253
#define CHAN_DROPPED                     254
#define CHAN_SET_SYNTAX                  255
#define CHAN_SET_DISABLED                256
#define CHAN_SET_UNKNOWN_OPTION          257
#define CHAN_SET_FOUNDER_TOO_MANY_CHANS  258
#define CHAN_FOUNDER_CHANGED             259
#define CHAN_SUCCESSOR_CHANGED           260
#define CHAN_SUCCESSOR_UNSET             261
#define CHAN_SET_PASSWORD_FAILED         262
#define CHAN_PASSWORD_CHANGED            263
#define CHAN_PASSWORD_CHANGED_TO         264
#define CHAN_DESC_CHANGED                265
#define CHAN_URL_CHANGED                 266
#define CHAN_URL_UNSET                   267
#define CHAN_EMAIL_CHANGED               268
#define CHAN_EMAIL_UNSET                 269
#define CHAN_ENTRY_MSG_CHANGED           270
#define CHAN_ENTRY_MSG_UNSET             271
#define CHAN_SET_TOPIC_FAILED            272
#define CHAN_SET_MLOCK_KEY_REQUIRED      273
#define CHAN_SET_MLOCK_LIMIT_REQUIRED    274
#define CHAN_SET_MLOCK_LIMIT_POSITIVE    275
#define CHAN_SET_MLOCK_UNKNOWN_CHAR      276
#define CHAN_MLOCK_CHANGED               277
#define CHAN_MLOCK_REMOVED               278
#define CHAN_SET_KEEPTOPIC_SYNTAX        279
#define CHAN_SET_KEEPTOPIC_ON            280
#define CHAN_SET_KEEPTOPIC_OFF           281
#define CHAN_SET_TOPICLOCK_SYNTAX        282
#define CHAN_SET_TOPICLOCK_ON            283
#define CHAN_SET_TOPICLOCK_OFF           284
#define CHAN_SET_PRIVATE_SYNTAX          285
#define CHAN_SET_PRIVATE_ON              286
#define CHAN_SET_PRIVATE_OFF             287
#define CHAN_SET_SECUREOPS_SYNTAX        288
#define CHAN_SET_SECUREOPS_ON            289
#define CHAN_SET_SECUREOPS_OFF           290
#define CHAN_SET_LEAVEOPS_SYNTAX         291
#define CHAN_SET_LEAVEOPS_ON             292
#define CHAN_SET_LEAVEOPS_OFF            293
#define CHAN_SET_RESTRICTED_SYNTAX       294
#define CHAN_SET_RESTRICTED_ON           295
#define CHAN_SET_RESTRICTED_OFF          296
#define CHAN_SET_SECURE_SYNTAX           297
#define CHAN_SET_SECURE_ON               298
#define CHAN_SET_SECURE_OFF              299
#define CHAN_SET_OPNOTICE_SYNTAX         300
#define CHAN_SET_OPNOTICE_ON             301
#define CHAN_SET_OPNOTICE_OFF            302
#define CHAN_SET_STAY_SYNTAX             303
#define CHAN_SET_STAY_ON                 304
#define CHAN_SET_STAY_OFF                305
#define CHAN_SET_NOEXPIRE_SYNTAX         306
#define CHAN_SET_NOEXPIRE_ON             307
#define CHAN_SET_NOEXPIRE_OFF            308
#define CHAN_ACCESS_SYNTAX               309
#define CHAN_ACCESS_DISABLED             310
#define CHAN_ACCESS_LEVEL_NONZERO        311
#define CHAN_ACCESS_LEVEL_RANGE          312
#define CHAN_ACCESS_NICKS_ONLY           313
#define CHAN_ACCESS_REACHED_LIMIT        314
#define CHAN_ACCESS_LEVEL_UNCHANGED      315
#define CHAN_ACCESS_LEVEL_CHANGED        316
#define CHAN_ACCESS_ADDED                317
#define CHAN_ACCESS_NO_SUCH_ENTRY        318
#define CHAN_ACCESS_NOT_FOUND            319
#define CHAN_ACCESS_NO_MATCH             320
#define CHAN_ACCESS_DELETED              321
#define CHAN_ACCESS_DELETED_ONE          322
#define CHAN_ACCESS_DELETED_SEVERAL      323
#define CHAN_ACCESS_LIST_HEADER          324
#define CHAN_ACCESS_LIST_EMPTY           325
#define CHAN_ACCESS_LIST_FORMAT          326
#define CHAN_NO_AOP_SOP                  327
#define CHAN_AKICK_SYNTAX                328
#define CHAN_AKICK_DISABLED              329
#define CHAN_AKICK_ALREADY_EXISTS        330
#define CHAN_AKICK_REACHED_LIMIT         331
#define CHAN_AKICK_ADDED                 332
#define CHAN_AKICK_NO_SUCH_ENTRY         333
#define CHAN_AKICK_NOT_FOUND             334
#define CHAN_AKICK_DELETED               335
#define CHAN_AKICK_DELETED_ONE           336
#define CHAN_AKICK_DELETED_SEVERAL       337
#define CHAN_AKICK_NO_MATCH              338
#define CHAN_AKICK_LIST_EMPTY            339
#define CHAN_AKICK_LIST_HEADER           340
#define CHAN_AKICK_LIST_FORMAT           341
#define CHAN_AKICK_ENFORCE_DONE          342
#define CHAN_LEVELS_SYNTAX               343
#define CHAN_LEVELS_RANGE                344
#define CHAN_LEVELS_CHANGED              345
#define CHAN_LEVELS_UNKNOWN              346
#define CHAN_LEVELS_DISABLED             347
#define CHAN_LEVELS_LIST_HEADER          348
#define CHAN_LEVELS_LIST_DISABLED        349
#define CHAN_LEVELS_LIST_FOUNDER         350
#define CHAN_LEVELS_LIST_NORMAL          351
#define CHAN_LEVELS_RESET                352
#define CHAN_INFO_SYNTAX                 353
#define CHAN_INFO_HEADER                 354
#define CHAN_INFO_ACTIVED                355
#define CHAN_INFO_SUSPENDED              356
#define CHAN_INFO_FOUNDER                357
#define CHAN_INFO_NO_FOUNDER             358
#define CHAN_INFO_SUCCESSOR              359
#define CHAN_INFO_NO_SUCCESSOR           360
#define CHAN_INFO_DESCRIPTION            361
#define CHAN_INFO_ENTRYMSG               362
#define CHAN_INFO_TIME_REGGED            363
#define CHAN_INFO_LAST_USED              364
#define CHAN_INFO_LAST_TOPIC             365
#define CHAN_INFO_TOPIC_SET_BY           366
#define CHAN_INFO_URL                    367
#define CHAN_INFO_EMAIL                  368
#define CHAN_INFO_OPTIONS                369
#define CHAN_INFO_OPT_PRIVATE            370
#define CHAN_INFO_OPT_KEEPTOPIC          371
#define CHAN_INFO_OPT_TOPICLOCK          372
#define CHAN_INFO_OPT_SECUREOPS          373
#define CHAN_INFO_OPT_LEAVEOPS           374
#define CHAN_INFO_OPT_RESTRICTED         375
#define CHAN_INFO_OPT_SECURE             376
#define CHAN_INFO_OPT_NONE               377
#define CHAN_INFO_MODE_LOCK              378
#define CHAN_INFO_NO_EXPIRE              379
#define CHAN_LIST_SYNTAX                 380
#define CHAN_LIST_HEADER                 381
#define CHAN_LIST_FORMAT                 382
#define CHAN_LIST_END                    383
#define CHAN_INVITE_SYNTAX               384
#define CHAN_OP_SYNTAX                   385
#define CHAN_DEOP_SYNTAX                 386
#define CHAN_VOICE_SYNTAX                387
#define CHAN_DEVOICE_SYNTAX              388
#define CHAN_KICK_SYNTAX                 389
#define CHAN_BAN_SYNTAX                  390
#define CHAN_UNBAN_SYNTAX                391
#define CHAN_UNBANNED                    392
#define CHAN_CLEAR_SYNTAX                393
#define CHAN_CLEARED_BANS                394
#define CHAN_CLEARED_MODES               395
#define CHAN_CLEARED_OPS                 396
#define CHAN_CLEARED_VOICES              397
#define CHAN_CLEARED_USERS               398
#define CHAN_RESET_SYNTAX                399
#define CHAN_GETPASS_SYNTAX              400
#define CHAN_GETPASS_UNAVAILABLE         401
#define CHAN_GETPASS_PASSWORD_IS         402
#define CHAN_SUSPEND_SYNTAX              403
#define CHAN_SUSPEND_SUCCEEDED           404
#define CHAN_SUSPEND_FAILED              405
#define CHAN_FORBID_SYNTAX               406
#define CHAN_FORBID_SUCCEEDED            407
#define CHAN_FORBID_FAILED               408
#define MEMO_HAVE_NEW_MEMO               409
#define MEMO_HAVE_NEW_MEMOS              410
#define MEMO_TYPE_READ_LAST              411
#define MEMO_TYPE_READ_NUM               412
#define MEMO_TYPE_LIST_NEW               413
#define MEMO_AT_LIMIT                    414
#define MEMO_OVER_LIMIT                  415
#define MEMO_NEW_MEMO_ARRIVED            416
#define MEMO_HAVE_NO_MEMOS               417
#define MEMO_X_HAS_NO_MEMOS              418
#define MEMO_DOES_NOT_EXIST              419
#define MEMO_LIST_NOT_FOUND              420
#define MEMO_SEND_SYNTAX                 421
#define MEMO_SEND_DISABLED               422
#define MEMO_SEND_PLEASE_WAIT            423
#define MEMO_X_GETS_NO_MEMOS             424
#define MEMO_X_HAS_TOO_MANY_MEMOS        425
#define MEMO_SENT                        426
#define MEMO_LIST_SYNTAX                 427
#define MEMO_HAVE_NO_NEW_MEMOS           428
#define MEMO_X_HAS_NO_NEW_MEMOS          429
#define MEMO_LIST_MEMOS                  430
#define MEMO_LIST_NEW_MEMOS              431
#define MEMO_LIST_CHAN_MEMOS             432
#define MEMO_LIST_CHAN_NEW_MEMOS         433
#define MEMO_LIST_HEADER                 434
#define MEMO_LIST_FORMAT                 435
#define MEMO_READ_SYNTAX                 436
#define MEMO_HEADER                      437
#define MEMO_CHAN_HEADER                 438
#define MEMO_TEXT                        439
#define MEMO_DEL_SYNTAX                  440
#define MEMO_DELETED_NONE                441
#define MEMO_DELETED_ONE                 442
#define MEMO_DELETED_SEVERAL             443
#define MEMO_DELETED_ALL                 444
#define MEMO_SET_SYNTAX                  445
#define MEMO_SET_DISABLED                446
#define MEMO_SET_UNKNOWN_OPTION          447
#define MEMO_SET_NOTIFY_SYNTAX           448
#define MEMO_SET_NOTIFY_ON               449
#define MEMO_SET_NOTIFY_LOGON            450
#define MEMO_SET_NOTIFY_NEW              451
#define MEMO_SET_NOTIFY_OFF              452
#define MEMO_SET_LIMIT_SYNTAX            453
#define MEMO_SET_LIMIT_SERVADMIN_SYNTAX  454
#define MEMO_SET_YOUR_LIMIT_FORBIDDEN    455
#define MEMO_SET_LIMIT_FORBIDDEN         456
#define MEMO_SET_YOUR_LIMIT_TOO_HIGH     457
#define MEMO_SET_LIMIT_TOO_HIGH          458
#define MEMO_SET_LIMIT_OVERFLOW          459
#define MEMO_SET_YOUR_LIMIT              460
#define MEMO_SET_YOUR_LIMIT_ZERO         461
#define MEMO_SET_LIMIT                   462
#define MEMO_SET_LIMIT_ZERO              463
#define MEMO_UNSET_YOUR_LIMIT            464
#define MEMO_UNSET_LIMIT                 465
#define MEMO_INFO_SYNTAX                 466
#define MEMO_INFO_SERVADMIN_SYNTAX       467
#define MEMO_INFO_NO_MEMOS               468
#define MEMO_INFO_MEMO                   469
#define MEMO_INFO_MEMO_UNREAD            470
#define MEMO_INFO_MEMOS                  471
#define MEMO_INFO_MEMOS_ONE_UNREAD       472
#define MEMO_INFO_MEMOS_SOME_UNREAD      473
#define MEMO_INFO_MEMOS_ALL_UNREAD       474
#define MEMO_INFO_LIMIT                  475
#define MEMO_INFO_HARD_LIMIT             476
#define MEMO_INFO_LIMIT_ZERO             477
#define MEMO_INFO_HARD_LIMIT_ZERO        478
#define MEMO_INFO_NO_LIMIT               479
#define MEMO_INFO_X_NO_MEMOS             480
#define MEMO_INFO_X_MEMO                 481
#define MEMO_INFO_X_MEMO_UNREAD          482
#define MEMO_INFO_X_MEMOS                483
#define MEMO_INFO_X_MEMOS_ONE_UNREAD     484
#define MEMO_INFO_X_MEMOS_SOME_UNREAD    485
#define MEMO_INFO_X_MEMOS_ALL_UNREAD     486
#define MEMO_INFO_X_LIMIT                487
#define MEMO_INFO_X_HARD_LIMIT           488
#define MEMO_INFO_X_NO_LIMIT             489
#define OPER_BOUNCY_MODES                490
#define OPER_BOUNCY_MODES_U_LINE         491
#define OPER_GLOBAL_SYNTAX               492
#define OPER_STATS_UNKNOWN_OPTION        493
#define OPER_STATS_CURRENT_USERS         494
#define OPER_STATS_MAX_USERS             495
#define OPER_STATS_UPTIME_DHMS           496
#define OPER_STATS_UPTIME_1DHMS          497
#define OPER_STATS_UPTIME_HMS            498
#define OPER_STATS_UPTIME_HM1S           499
#define OPER_STATS_UPTIME_H1MS           500
#define OPER_STATS_UPTIME_H1M1S          501
#define OPER_STATS_UPTIME_1HMS           502
#define OPER_STATS_UPTIME_1HM1S          503
#define OPER_STATS_UPTIME_1H1MS          504
#define OPER_STATS_UPTIME_1H1M1S         505
#define OPER_STATS_UPTIME_MS             506
#define OPER_STATS_UPTIME_M1S            507
#define OPER_STATS_UPTIME_1MS            508
#define OPER_STATS_UPTIME_1M1S           509
#define OPER_STATS_BYTES_READ            510
#define OPER_STATS_BYTES_WRITTEN         511
#define OPER_STATS_SERVER_MEM            512
#define OPER_STATS_USER_MEM              513
#define OPER_STATS_CHANNEL_MEM           514
#define OPER_STATS_NICKSERV_MEM          515
#define OPER_STATS_CHANSERV_MEM          516
#define OPER_STATS_OPERSERV_MEM          517
#define OPER_STATS_AKILL_COUNT           518
#define OPER_STATS_AKILL_EXPIRE_DAYS     519
#define OPER_STATS_AKILL_EXPIRE_DAY      520
#define OPER_STATS_AKILL_EXPIRE_HOURS    521
#define OPER_STATS_AKILL_EXPIRE_HOUR     522
#define OPER_STATS_AKILL_EXPIRE_MINS     523
#define OPER_STATS_AKILL_EXPIRE_MIN      524
#define OPER_STATS_AKILL_EXPIRE_NONE     525
#define OPER_STATS_SESSIONS_MEM          526
#define OPER_MODE_SYNTAX                 527
#define OPER_CLEARMODES_SYNTAX           528
#define OPER_CLEARMODES_DONE             529
#define OPER_CLEARMODES_ALL_DONE         530
#define OPER_KICK_SYNTAX                 531
#define OPER_ADMIN_SYNTAX                532
#define OPER_ADMIN_ADD_SYNTAX            533
#define OPER_ADMIN_DEL_SYNTAX            534
#define OPER_ADMIN_SKELETON              535
#define OPER_ADMIN_EXISTS                536
#define OPER_ADMIN_ADDED                 537
#define OPER_ADMIN_TOO_MANY              538
#define OPER_ADMIN_REMOVED               539
#define OPER_ADMIN_NOT_FOUND             540
#define OPER_ADMIN_LIST_HEADER           541
#define OPER_OPER_SYNTAX                 542
#define OPER_OPER_ADD_SYNTAX             543
#define OPER_OPER_DEL_SYNTAX             544
#define OPER_OPER_SKELETON               545
#define OPER_OPER_EXISTS                 546
#define OPER_OPER_ADDED                  547
#define OPER_OPER_TOO_MANY               548
#define OPER_OPER_REMOVED                549
#define OPER_OPER_NOT_FOUND              550
#define OPER_OPER_LIST_HEADER            551
#define OPER_AKILL_SYNTAX                552
#define OPER_AKILL_ADD_SYNTAX            553
#define OPER_AKILL_DEL_SYNTAX            554
#define OPER_TOO_MANY_AKILLS             555
#define OPER_AKILL_NO_NICK               556
#define OPER_AKILL_ADDED                 557
#define OPER_AKILL_REMOVED               558
#define OPER_AKILL_NOT_FOUND             559
#define OPER_AKILL_LIST_HEADER           560
#define OPER_AKILL_LIST_FORMAT           561
#define OPER_AKILL_VIEW_FORMAT           562
#define OPER_AKILL_NO_EXPIRE             563
#define OPER_AKILL_EXPIRES_SOON          564
#define OPER_AKILL_EXPIRES_M             565
#define OPER_AKILL_EXPIRES_1M            566
#define OPER_AKILL_EXPIRES_HM            567
#define OPER_AKILL_EXPIRES_H1M           568
#define OPER_AKILL_EXPIRES_1HM           569
#define OPER_AKILL_EXPIRES_1H1M          570
#define OPER_AKILL_EXPIRES_D             571
#define OPER_AKILL_EXPIRES_1D            572
#define OPER_SET_SYNTAX                  573
#define OPER_SET_IGNORE_ON               574
#define OPER_SET_IGNORE_OFF              575
#define OPER_SET_IGNORE_ERROR            576
#define OPER_SET_READONLY_ON             577
#define OPER_SET_READONLY_OFF            578
#define OPER_SET_READONLY_ERROR          579
#define OPER_SET_DEBUG_ON                580
#define OPER_SET_DEBUG_OFF               581
#define OPER_SET_DEBUG_LEVEL             582
#define OPER_SET_DEBUG_ERROR             583
#define OPER_SET_UNKNOWN_OPTION          584
#define OPER_JUPE_SYNTAX                 585
#define OPER_RAW_SYNTAX                  586
#define OPER_UPDATING                    587
#define OPER_CANNOT_RESTART              588
#define OPER_IGNORE_LIST                 589
#define OPER_IGNORE_LIST_EMPTY           590
#define OPER_ROTATELOG_FILE_EXISTS       591
#define OPER_ROTATELOG_RENAME_DONE       592
#define OPER_ROTATELOG_RENAME_FAIL       593
#define OPER_ROTATELOG_OPEN_LOG_FAIL     594
#define CYBER_NO_ADMIN_CYBER             595
#define CYBER_NICK_NOT_IN_CYBER          596
#define CYBER_KILL_SYNTAX                597
#define CYBER_KILL_SUCCEEDED             598
#define CYBER_GLINE_SYNTAX               599
#define CYBER_GLINE_SUCCEEDED            600
#define CYBER_UNBAN_SYNTAX               601
#define CYBER_UNBAN_FAILED               602
#define CYBER_UNBAN_SUCCEEDED            603
#define OPER_EXCEPTION_SYNTAX            604
#define OPER_EXCEPTION_ADD_SYNTAX        605
#define OPER_EXCEPTION_DEL_SYNTAX        606
#define OPER_EXCEPTION_MOVE_SYNTAX       607
#define OPER_EXCEPTION_DISABLED          608
#define OPER_EXCEPTION_ALREADY_PRESENT   609
#define OPER_EXCEPTION_TOO_MANY          610
#define OPER_EXCEPTION_ADDED             611
#define OPER_EXCEPTION_MOVED             612
#define OPER_EXCEPTION_NO_SUCH_ENTRY     613
#define OPER_EXCEPTION_NOT_FOUND         614
#define OPER_EXCEPTION_NO_MATCH          615
#define OPER_EXCEPTION_DELETED           616
#define OPER_EXCEPTION_DELETED_ONE       617
#define OPER_EXCEPTION_DELETED_SEVERAL   618
#define OPER_EXCEPTION_LIST_HEADER       619
#define OPER_EXCEPTION_LIST_FORMAT       620
#define OPER_EXCEPTION_LIST_COLHEAD      621
#define OPER_EXCEPTION_VIEW_FORMAT       622
#define OPER_EXCEPTION_INVALID_LIMIT     623
#define OPER_EXCEPTION_INVALID_HOSTMASK  624
#define OPER_SESSION_SYNTAX              625
#define OPER_SESSION_LIST_SYNTAX         626
#define OPER_SESSION_VIEW_SYNTAX         627
#define OPER_SESSION_DISABLED            628
#define OPER_SESSION_INVALID_THRESHOLD   629
#define OPER_SESSION_NOT_FOUND           630
#define OPER_SESSION_LIST_HEADER         631
#define OPER_SESSION_LIST_COLHEAD        632
#define OPER_SESSION_LIST_FORMAT         633
#define OPER_SESSION_VIEW_FORMAT         634
#define CYBER_CLONES_IS_CYBER            635
#define CYBER_CLONES_NOT_IS_CYBER        636
#define OPER_KILLCLONES_SYNTAX           637
#define OPER_KILLCLONES_UNKNOWN_NICK     638
#define CYBER_KILLCLONES_SUCCEEDED       639
#define NEWS_LOGON_TEXT                  640
#define NEWS_OPER_TEXT                   641
#define NEWS_LOGON_SYNTAX                642
#define NEWS_LOGON_LIST_HEADER           643
#define NEWS_LOGON_LIST_ENTRY            644
#define NEWS_LOGON_LIST_NONE             645
#define NEWS_LOGON_ADD_SYNTAX            646
#define NEWS_LOGON_ADD_FULL              647
#define NEWS_LOGON_ADDED                 648
#define NEWS_LOGON_DEL_SYNTAX            649
#define NEWS_LOGON_DEL_NOT_FOUND         650
#define NEWS_LOGON_DELETED               651
#define NEWS_LOGON_DEL_NONE              652
#define NEWS_LOGON_DELETED_ALL           653
#define NEWS_OPER_SYNTAX                 654
#define NEWS_OPER_LIST_HEADER            655
#define NEWS_OPER_LIST_ENTRY             656
#define NEWS_OPER_LIST_NONE              657
#define NEWS_OPER_ADD_SYNTAX             658
#define NEWS_OPER_ADD_FULL               659
#define NEWS_OPER_ADDED                  660
#define NEWS_OPER_DEL_SYNTAX             661
#define NEWS_OPER_DEL_NOT_FOUND          662
#define NEWS_OPER_DELETED                663
#define NEWS_OPER_DEL_NONE               664
#define NEWS_OPER_DELETED_ALL            665
#define NEWS_HELP_LOGON                  666
#define NEWS_HELP_OPER                   667
#define NICK_HELP                        668
#define NICK_HELP_EXPIRE_ZERO            669
#define NICK_HELP_REGISTER               670
#define NICK_HELP_IDENTIFY               671
#define NICK_HELP_DROP                   672
#define NICK_HELP_ACCESS                 673
#define NICK_HELP_LINK                   674
#define NICK_HELP_UNLINK                 675
#define NICK_HELP_SET                    676
#define NICK_HELP_SET_PASSWORD           677
#define NICK_HELP_SET_LANGUAGE           678
#define NICK_HELP_SET_URL                679
#define NICK_HELP_SET_EMAIL              680
#define NICK_HELP_SET_KILL               681
#define NICK_HELP_SET_SECURE             682
#define NICK_HELP_SET_PRIVATE            683
#define NICK_HELP_SET_HIDE               684
#define NICK_HELP_SET_VHOST              685
#define NICK_HELP_RECOVER                686
#define NICK_HELP_RELEASE                687
#define NICK_HELP_GHOST                  688
#define NICK_HELP_INFO                   689
#define NICK_HELP_LIST                   690
#define NICK_HELP_STATUS                 691
#define NICK_SERVADMIN_HELP              692
#define NICK_SERVADMIN_HELP_USERIP       693
#define NICK_SERVADMIN_HELP_RENAME       694
#define NICK_SERVADMIN_HELP_DROP         695
#define NICK_SERVADMIN_HELP_SET          696
#define NICK_SERVADMIN_HELP_SET_NOEXPIRE 697
#define NICK_SERVADMIN_HELP_UNLINK       698
#define NICK_SERVADMIN_HELP_LISTLINKS    699
#define NICK_SERVADMIN_HELP_INFO         700
#define NICK_SERVADMIN_HELP_LIST         701
#define NICK_SERVADMIN_HELP_SENDPASS     702
#define NICK_SERVADMIN_HELP_GETPASS      703
#define NICK_SERVADMIN_HELP_SUSPEND      704
#define NICK_SERVADMIN_HELP_UNSUSPEND    705
#define NICK_SERVADMIN_HELP_FORBID       706
#define NICK_SERVADMIN_HELP_UNFORBID     707
#define CHAN_HELP                        708
#define CHAN_HELP_EXPIRES                709
#define CHAN_HELP_REGISTER               710
#define CHAN_HELP_IDENTIFY               711
#define CHAN_HELP_DROP                   712
#define CHAN_HELP_SET                    713
#define CHAN_HELP_SET_FOUNDER            714
#define CHAN_HELP_SET_SUCCESSOR          715
#define CHAN_HELP_SET_PASSWORD           716
#define CHAN_HELP_SET_DESC               717
#define CHAN_HELP_SET_URL                718
#define CHAN_HELP_SET_EMAIL              719
#define CHAN_HELP_SET_ENTRYMSG           720
#define CHAN_HELP_SET_TOPIC              721
#define CHAN_HELP_SET_KEEPTOPIC          722
#define CHAN_HELP_SET_TOPICLOCK          723
#define CHAN_HELP_SET_MLOCK              724
#define CHAN_HELP_SET_PRIVATE            725
#define CHAN_HELP_SET_RESTRICTED         726
#define CHAN_HELP_SET_SECURE             727
#define CHAN_HELP_SET_SECUREOPS          728
#define CHAN_HELP_SET_LEAVEOPS           729
#define CHAN_HELP_SET_OPNOTICE           730
#define CHAN_HELP_SET_STAY               731
#define CHAN_HELP_ACCESS                 732
#define CHAN_HELP_ACCESS_LEVELS          733
#define CHAN_HELP_AKICK                  734
#define CHAN_HELP_LEVELS                 735
#define CHAN_HELP_LEVELS_DESC            736
#define CHAN_HELP_LEVELS_DESC_FORMAT     737
#define CHAN_HELP_INFO                   738
#define CHAN_HELP_LIST                   739
#define CHAN_HELP_OP                     740
#define CHAN_HELP_DEOP                   741
#define CHAN_HELP_VOICE                  742
#define CHAN_HELP_DEVOICE                743
#define CHAN_HELP_INVITE                 744
#define CHAN_HELP_KICK                   745
#define CHAN_HELP_BAN                    746
#define CHAN_HELP_UNBAN                  747
#define CHAN_HELP_CLEAR                  748
#define CHAN_HELP_RESET                  749
#define CHAN_HELP_VERIFY                 750
#define CHAN_HELP_DELACCESS              751
#define CHAN_SYNTAX_DELACCESS            752
#define CHAN_MSG_DELACCESS_SUCCESS       753
#define CHAN_MSG_DELACCESS_NEG           754
#define CHAN_HELP_IRCOPS                 755
#define CHAN_SERVADMIN_HELP              756
#define CHAN_SERVADMIN_HELP_DROP         757
#define CHAN_SERVADMIN_HELP_SET          758
#define CHAN_SERVADMIN_HELP_SET_NOEXPIRE 759
#define CHAN_SERVADMIN_HELP_INFO         760
#define CHAN_SERVADMIN_HELP_LIST         761
#define CHAN_SERVADMIN_HELP_GETPASS      762
#define CHAN_SERVADMIN_HELP_SUSPEND      763
#define CHAN_SERVADMIN_HELP_UNSUSPEND    764
#define CHAN_SERVADMIN_HELP_FORBID       765
#define CHAN_SERVADMIN_HELP_UNFORBID     766
#define CHAN_SERVADMIN_HELP_STATUS       767
#define MEMO_HELP                        768
#define MEMO_HELP_SEND                   769
#define MEMO_HELP_LIST                   770
#define MEMO_HELP_READ                   771
#define MEMO_HELP_DEL                    772
#define MEMO_HELP_SET                    773
#define MEMO_HELP_SET_NOTIFY             774
#define MEMO_HELP_SET_LIMIT              775
#define MEMO_HELP_INFO                   776
#define MEMO_SERVADMIN_HELP_SET_LIMIT    777
#define MEMO_SERVADMIN_HELP_INFO         778
#define OPER_HELP                        779
#define OPER_HELP_GLOBAL                 780
#define OPER_HELP_VHOST                  781
#define OPER_HELP_KILL                   782
#define OPER_VHOST_SYNTAX                783
#define OPER_VHOST_SET                   784
#define OPER_VHOST_UNSET                 785
#define OPER_KILL_SUCCESS                786
#define OPER_HELP_STATS                  787
#define OPER_HELP_OPER                   788
#define OPER_HELP_ADMIN                  789
#define OPER_HELP_MODE                   790
#define OPER_HELP_CLEARMODES             791
#define OPER_HELP_KICK                   792
#define OPER_HELP_AKILL                  793
#define OPER_HELP_JUPE                   794
#define OPER_HELP_RAW                    795
#define OPER_HELP_SET                    796
#define OPER_HELP_SET_READONLY           797
#define OPER_HELP_SET_DEBUG              798
#define OPER_HELP_UPDATE                 799
#define OPER_HELP_QUIT                   800
#define OPER_HELP_SHUTDOWN               801
#define OPER_HELP_RESTART                802
#define OPER_HELP_ROTATELOG              803
#define CYBER_HELP                       804
#define CYBER_HELP_KILL                  805
#define CYBER_HELP_GLINE                 806
#define CYBER_HELP_UNBAN                 807
#define CYBER_HELP_CLONES                808
#define CYBER_SERVADMIN_HELP             809
#define OPER_HELP_EXCEPTION              810
#define OPER_HELP_SESSION                811
#define OPER_HELP_KILLCLONES             812
#define CREG_HELP                        813
#define CREG_HELP_REGISTRA               814
#define CREG_HELP_APOYA                  815
#define CREG_HELP_CANCELA                816
#define CREG_HELP_ESTADO                 817
#define CREG_HELP_APOYOS                 818
#define CREG_SERVADMIN_HELP              819
#define SERVICES_CREDITS                 820
#define BDD_HELP                         821
#define BDD_HELP_COMPACTAR               822
#define BDD_HELP_REGENERAR               823
#define BDD_HELP_ACTUALIZAR              824
#define BDD_HELP_TOCAR                   825
#define BDD_REG_SUCCESS                  826
#define BDD_COMPACT                      827
#define BDD_TOCAR_SYNTAX                 828
#define BDD_ERR_TABLE                    829
#define BDD_SEQ_OK                       830

#define NUM_STRINGS 831
